name: Build Windows Executable

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install --upgrade pip && pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile --name TriA-Webserver main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: TriA-Webserver
        path: dist/TriA-Webserver.exe
